"""empty message

Revision ID: 1801292017d5
Revises: c8f64c8333d2
Create Date: 2024-06-18 14:19:22.985449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1801292017d5'
down_revision = 'c8f64c8333d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_model_info',
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_executable', sa.Boolean(), nullable=True),
    sa.Column('fault_or_suspend_on_exception', sa.String(), nullable=True),
    sa.Column('process_group', sa.String(), nullable=True),
    sa.Column('content', sa.LargeBinary(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('bpmn_version_control_identifier', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('process_id')
    )
    # with op.batch_alter_table('task', schema=None) as batch_op:
    #     batch_op.drop_constraint('guid', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('task', schema=None) as batch_op:
    #     batch_op.create_unique_constraint('guid', ['guid'])

    op.drop_table('process_model_info')
    # ### end Alembic commands ###
