"""empty message

Revision ID: 384e2bbda36b
Revises: 1801292017d5
Create Date: 2024-06-20 13:46:51.568998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '384e2bbda36b'
down_revision = '1801292017d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('process_model_info', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               type_=sa.LargeBinary(),
               existing_nullable=True,
                              postgresql_using="content::bytea")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('process_model_info', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.LargeBinary(),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
