"""empty message

Revision ID: da22d9039670
Revises: 384e2bbda36b
Create Date: 2024-09-17 15:13:48.384925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da22d9039670'
down_revision = '384e2bbda36b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('human_task_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ended_at_in_seconds', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at_in_seconds', sa.Integer(), nullable=True))

    # with op.batch_alter_table('task', schema=None) as batch_op:
    #     batch_op.drop_constraint('guid', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('task', schema=None) as batch_op:
    #     batch_op.create_unique_constraint('guid', ['guid'])

    with op.batch_alter_table('human_task_user', schema=None) as batch_op:
        batch_op.drop_column('created_at_in_seconds')
        batch_op.drop_column('ended_at_in_seconds')

    # ### end Alembic commands ###
